// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf-spec/edicenter.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point3D struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point3D) Reset()         { *m = Point3D{} }
func (m *Point3D) String() string { return proto.CompactTextString(m) }
func (*Point3D) ProtoMessage()    {}
func (*Point3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{0}
}

func (m *Point3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point3D.Unmarshal(m, b)
}
func (m *Point3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point3D.Marshal(b, m, deterministic)
}
func (m *Point3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point3D.Merge(m, src)
}
func (m *Point3D) XXX_Size() int {
	return xxx_messageInfo_Point3D.Size(m)
}
func (m *Point3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Point3D.DiscardUnknown(m)
}

var xxx_messageInfo_Point3D proto.InternalMessageInfo

func (m *Point3D) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point3D) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Point3D) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type PopulatedSystemBriefInfo struct {
	Allegiance           string   `protobuf:"bytes,1,opt,name=allegiance,proto3" json:"allegiance,omitempty"`
	Government           string   `protobuf:"bytes,2,opt,name=government,proto3" json:"government,omitempty"`
	Faction              string   `protobuf:"bytes,3,opt,name=faction,proto3" json:"faction,omitempty"`
	FactionState         string   `protobuf:"bytes,4,opt,name=faction_state,json=factionState,proto3" json:"faction_state,omitempty"`
	Population           int64    `protobuf:"varint,5,opt,name=population,proto3" json:"population,omitempty"`
	Reserve              string   `protobuf:"bytes,6,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Security             string   `protobuf:"bytes,7,opt,name=security,proto3" json:"security,omitempty"`
	Economy              string   `protobuf:"bytes,8,opt,name=economy,proto3" json:"economy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopulatedSystemBriefInfo) Reset()         { *m = PopulatedSystemBriefInfo{} }
func (m *PopulatedSystemBriefInfo) String() string { return proto.CompactTextString(m) }
func (*PopulatedSystemBriefInfo) ProtoMessage()    {}
func (*PopulatedSystemBriefInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{1}
}

func (m *PopulatedSystemBriefInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopulatedSystemBriefInfo.Unmarshal(m, b)
}
func (m *PopulatedSystemBriefInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopulatedSystemBriefInfo.Marshal(b, m, deterministic)
}
func (m *PopulatedSystemBriefInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopulatedSystemBriefInfo.Merge(m, src)
}
func (m *PopulatedSystemBriefInfo) XXX_Size() int {
	return xxx_messageInfo_PopulatedSystemBriefInfo.Size(m)
}
func (m *PopulatedSystemBriefInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PopulatedSystemBriefInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PopulatedSystemBriefInfo proto.InternalMessageInfo

func (m *PopulatedSystemBriefInfo) GetAllegiance() string {
	if m != nil {
		return m.Allegiance
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetGovernment() string {
	if m != nil {
		return m.Government
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetFaction() string {
	if m != nil {
		return m.Faction
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetFactionState() string {
	if m != nil {
		return m.FactionState
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetPopulation() int64 {
	if m != nil {
		return m.Population
	}
	return 0
}

func (m *PopulatedSystemBriefInfo) GetReserve() string {
	if m != nil {
		return m.Reserve
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetSecurity() string {
	if m != nil {
		return m.Security
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetEconomy() string {
	if m != nil {
		return m.Economy
	}
	return ""
}

type SystemSummary struct {
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Coords               *Point3D                  `protobuf:"bytes,2,opt,name=coords,proto3" json:"coords,omitempty"`
	PopSystemInfo        *PopulatedSystemBriefInfo `protobuf:"bytes,3,opt,name=pop_system_info,json=popSystemInfo,proto3" json:"pop_system_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SystemSummary) Reset()         { *m = SystemSummary{} }
func (m *SystemSummary) String() string { return proto.CompactTextString(m) }
func (*SystemSummary) ProtoMessage()    {}
func (*SystemSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{2}
}

func (m *SystemSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemSummary.Unmarshal(m, b)
}
func (m *SystemSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemSummary.Marshal(b, m, deterministic)
}
func (m *SystemSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemSummary.Merge(m, src)
}
func (m *SystemSummary) XXX_Size() int {
	return xxx_messageInfo_SystemSummary.Size(m)
}
func (m *SystemSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemSummary.DiscardUnknown(m)
}

var xxx_messageInfo_SystemSummary proto.InternalMessageInfo

func (m *SystemSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SystemSummary) GetCoords() *Point3D {
	if m != nil {
		return m.Coords
	}
	return nil
}

func (m *SystemSummary) GetPopSystemInfo() *PopulatedSystemBriefInfo {
	if m != nil {
		return m.PopSystemInfo
	}
	return nil
}

type DockableStationShortInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LandingPad           string   `protobuf:"bytes,2,opt,name=landing_pad,json=landingPad,proto3" json:"landing_pad,omitempty"`
	Distance             float64  `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Planetary            bool     `protobuf:"varint,4,opt,name=planetary,proto3" json:"planetary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockableStationShortInfo) Reset()         { *m = DockableStationShortInfo{} }
func (m *DockableStationShortInfo) String() string { return proto.CompactTextString(m) }
func (*DockableStationShortInfo) ProtoMessage()    {}
func (*DockableStationShortInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{3}
}

func (m *DockableStationShortInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockableStationShortInfo.Unmarshal(m, b)
}
func (m *DockableStationShortInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockableStationShortInfo.Marshal(b, m, deterministic)
}
func (m *DockableStationShortInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockableStationShortInfo.Merge(m, src)
}
func (m *DockableStationShortInfo) XXX_Size() int {
	return xxx_messageInfo_DockableStationShortInfo.Size(m)
}
func (m *DockableStationShortInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DockableStationShortInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DockableStationShortInfo proto.InternalMessageInfo

func (m *DockableStationShortInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DockableStationShortInfo) GetLandingPad() string {
	if m != nil {
		return m.LandingPad
	}
	return ""
}

func (m *DockableStationShortInfo) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *DockableStationShortInfo) GetPlanetary() bool {
	if m != nil {
		return m.Planetary
	}
	return false
}

type SystemByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemByNameRequest) Reset()         { *m = SystemByNameRequest{} }
func (m *SystemByNameRequest) String() string { return proto.CompactTextString(m) }
func (*SystemByNameRequest) ProtoMessage()    {}
func (*SystemByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{4}
}

func (m *SystemByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemByNameRequest.Unmarshal(m, b)
}
func (m *SystemByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemByNameRequest.Marshal(b, m, deterministic)
}
func (m *SystemByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemByNameRequest.Merge(m, src)
}
func (m *SystemByNameRequest) XXX_Size() int {
	return xxx_messageInfo_SystemByNameRequest.Size(m)
}
func (m *SystemByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemByNameRequest proto.InternalMessageInfo

func (m *SystemByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SystemsDistanceRequest struct {
	Name1                string   `protobuf:"bytes,1,opt,name=name1,proto3" json:"name1,omitempty"`
	Name2                string   `protobuf:"bytes,2,opt,name=name2,proto3" json:"name2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemsDistanceRequest) Reset()         { *m = SystemsDistanceRequest{} }
func (m *SystemsDistanceRequest) String() string { return proto.CompactTextString(m) }
func (*SystemsDistanceRequest) ProtoMessage()    {}
func (*SystemsDistanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{5}
}

func (m *SystemsDistanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemsDistanceRequest.Unmarshal(m, b)
}
func (m *SystemsDistanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemsDistanceRequest.Marshal(b, m, deterministic)
}
func (m *SystemsDistanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemsDistanceRequest.Merge(m, src)
}
func (m *SystemsDistanceRequest) XXX_Size() int {
	return xxx_messageInfo_SystemsDistanceRequest.Size(m)
}
func (m *SystemsDistanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemsDistanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemsDistanceRequest proto.InternalMessageInfo

func (m *SystemsDistanceRequest) GetName1() string {
	if m != nil {
		return m.Name1
	}
	return ""
}

func (m *SystemsDistanceRequest) GetName2() string {
	if m != nil {
		return m.Name2
	}
	return ""
}

type SystemsDistanceReply struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Distance             float64  `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemsDistanceReply) Reset()         { *m = SystemsDistanceReply{} }
func (m *SystemsDistanceReply) String() string { return proto.CompactTextString(m) }
func (*SystemsDistanceReply) ProtoMessage()    {}
func (*SystemsDistanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{6}
}

func (m *SystemsDistanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemsDistanceReply.Unmarshal(m, b)
}
func (m *SystemsDistanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemsDistanceReply.Marshal(b, m, deterministic)
}
func (m *SystemsDistanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemsDistanceReply.Merge(m, src)
}
func (m *SystemsDistanceReply) XXX_Size() int {
	return xxx_messageInfo_SystemsDistanceReply.Size(m)
}
func (m *SystemsDistanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemsDistanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_SystemsDistanceReply proto.InternalMessageInfo

func (m *SystemsDistanceReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SystemsDistanceReply) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type SystemSummaryReply struct {
	Error                string         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Summary              *SystemSummary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SystemSummaryReply) Reset()         { *m = SystemSummaryReply{} }
func (m *SystemSummaryReply) String() string { return proto.CompactTextString(m) }
func (*SystemSummaryReply) ProtoMessage()    {}
func (*SystemSummaryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{7}
}

func (m *SystemSummaryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemSummaryReply.Unmarshal(m, b)
}
func (m *SystemSummaryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemSummaryReply.Marshal(b, m, deterministic)
}
func (m *SystemSummaryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemSummaryReply.Merge(m, src)
}
func (m *SystemSummaryReply) XXX_Size() int {
	return xxx_messageInfo_SystemSummaryReply.Size(m)
}
func (m *SystemSummaryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemSummaryReply.DiscardUnknown(m)
}

var xxx_messageInfo_SystemSummaryReply proto.InternalMessageInfo

func (m *SystemSummaryReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SystemSummaryReply) GetSummary() *SystemSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

type DockableStationsReply struct {
	Error                string                      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Stations             []*DockableStationShortInfo `protobuf:"bytes,2,rep,name=stations,proto3" json:"stations,omitempty"`
	SuggestedSystems     []string                    `protobuf:"bytes,3,rep,name=suggested_systems,json=suggestedSystems,proto3" json:"suggested_systems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DockableStationsReply) Reset()         { *m = DockableStationsReply{} }
func (m *DockableStationsReply) String() string { return proto.CompactTextString(m) }
func (*DockableStationsReply) ProtoMessage()    {}
func (*DockableStationsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{8}
}

func (m *DockableStationsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockableStationsReply.Unmarshal(m, b)
}
func (m *DockableStationsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockableStationsReply.Marshal(b, m, deterministic)
}
func (m *DockableStationsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockableStationsReply.Merge(m, src)
}
func (m *DockableStationsReply) XXX_Size() int {
	return xxx_messageInfo_DockableStationsReply.Size(m)
}
func (m *DockableStationsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DockableStationsReply.DiscardUnknown(m)
}

var xxx_messageInfo_DockableStationsReply proto.InternalMessageInfo

func (m *DockableStationsReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DockableStationsReply) GetStations() []*DockableStationShortInfo {
	if m != nil {
		return m.Stations
	}
	return nil
}

func (m *DockableStationsReply) GetSuggestedSystems() []string {
	if m != nil {
		return m.SuggestedSystems
	}
	return nil
}

func init() {
	proto.RegisterType((*Point3D)(nil), "api.Point3D")
	proto.RegisterType((*PopulatedSystemBriefInfo)(nil), "api.PopulatedSystemBriefInfo")
	proto.RegisterType((*SystemSummary)(nil), "api.SystemSummary")
	proto.RegisterType((*DockableStationShortInfo)(nil), "api.DockableStationShortInfo")
	proto.RegisterType((*SystemByNameRequest)(nil), "api.SystemByNameRequest")
	proto.RegisterType((*SystemsDistanceRequest)(nil), "api.SystemsDistanceRequest")
	proto.RegisterType((*SystemsDistanceReply)(nil), "api.SystemsDistanceReply")
	proto.RegisterType((*SystemSummaryReply)(nil), "api.SystemSummaryReply")
	proto.RegisterType((*DockableStationsReply)(nil), "api.DockableStationsReply")
}

func init() { proto.RegisterFile("protobuf-spec/edicenter.proto", fileDescriptor_e4ecdf5e536227fd) }

var fileDescriptor_e4ecdf5e536227fd = []byte{
	// 602 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0x4f, 0x73, 0xd3, 0x3e,
	0x10, 0xfd, 0x39, 0x69, 0x9b, 0x64, 0x93, 0xce, 0xaf, 0xa8, 0x05, 0x44, 0xa0, 0x90, 0x31, 0x1c,
	0xca, 0x00, 0x65, 0x48, 0x4f, 0x5c, 0x21, 0x9d, 0xc0, 0x01, 0xa6, 0xe3, 0x5e, 0xb8, 0x65, 0x54,
	0x7b, 0x13, 0x3c, 0xd8, 0x92, 0x90, 0x94, 0x4e, 0xdd, 0x6f, 0xd0, 0x1b, 0x17, 0x3e, 0x27, 0x5f,
	0x81, 0xd1, 0x1f, 0x87, 0xa4, 0x84, 0xdc, 0xfc, 0x76, 0x9f, 0x9e, 0x77, 0xdf, 0x93, 0x0d, 0x87,
	0x52, 0x09, 0x23, 0x2e, 0xe6, 0xd3, 0x57, 0x5a, 0x62, 0xfa, 0x1a, 0xb3, 0x3c, 0x45, 0x6e, 0x50,
	0x1d, 0xbb, 0x3a, 0x69, 0x32, 0x99, 0xc7, 0x27, 0xd0, 0x3a, 0x13, 0x39, 0x37, 0x27, 0x23, 0xd2,
	0x83, 0xe8, 0x8a, 0x46, 0x83, 0xe8, 0x28, 0x4a, 0xa2, 0x2b, 0x8b, 0x2a, 0xda, 0xf0, 0xa8, 0xb2,
	0xe8, 0x9a, 0x36, 0x3d, 0xba, 0x8e, 0x6f, 0x1a, 0x40, 0xcf, 0x84, 0x9c, 0x17, 0xcc, 0x60, 0x76,
	0x5e, 0x69, 0x83, 0xe5, 0x3b, 0x95, 0xe3, 0xf4, 0x23, 0x9f, 0x0a, 0xf2, 0x18, 0x80, 0x15, 0x05,
	0xce, 0x72, 0xc6, 0x53, 0x74, 0x7a, 0x9d, 0x64, 0xa9, 0x62, 0xfb, 0x33, 0x71, 0x89, 0x8a, 0x97,
	0xc8, 0x8d, 0x7b, 0x43, 0x27, 0x59, 0xaa, 0x10, 0x0a, 0xad, 0x29, 0x4b, 0x4d, 0x2e, 0xb8, 0x7b,
	0x61, 0x27, 0xa9, 0x21, 0x79, 0x0a, 0xbb, 0xe1, 0x71, 0xa2, 0x0d, 0x33, 0x48, 0xb7, 0x5c, 0xbf,
	0x17, 0x8a, 0xe7, 0xb6, 0x66, 0xe5, 0xa5, 0x1f, 0xcd, 0x2a, 0x6c, 0x0f, 0xa2, 0xa3, 0x66, 0xb2,
	0x54, 0xb1, 0xf2, 0x0a, 0x35, 0xaa, 0x4b, 0xa4, 0x3b, 0x5e, 0x3e, 0x40, 0xd2, 0x87, 0xb6, 0xc6,
	0x74, 0xae, 0x72, 0x53, 0xd1, 0x96, 0x6b, 0x2d, 0xb0, 0x3d, 0x85, 0xa9, 0xe0, 0xa2, 0xac, 0x68,
	0xdb, 0x9f, 0x0a, 0x30, 0xfe, 0x11, 0xc1, 0xae, 0xb7, 0xe0, 0x7c, 0x5e, 0x96, 0x4c, 0x55, 0x84,
	0xc0, 0x16, 0x67, 0x65, 0xbd, 0xba, 0x7b, 0x26, 0xcf, 0x60, 0x27, 0x15, 0x42, 0x65, 0xda, 0x2d,
	0xdc, 0x1d, 0xf6, 0x8e, 0x99, 0xcc, 0x8f, 0x83, 0xf3, 0x49, 0xe8, 0x91, 0x53, 0xf8, 0x5f, 0x0a,
	0x39, 0xd1, 0x4e, 0x6e, 0x92, 0xf3, 0xa9, 0x70, 0x16, 0x74, 0x87, 0x87, 0x81, 0xbe, 0xde, 0xf2,
	0x64, 0x57, 0x0a, 0xe9, 0x6b, 0x16, 0xc6, 0x37, 0x11, 0xd0, 0x91, 0x48, 0xbf, 0xb1, 0x8b, 0x02,
	0xad, 0x29, 0xd6, 0x9b, 0xaf, 0x42, 0x19, 0x17, 0xcf, 0xba, 0xe9, 0x9e, 0x40, 0xb7, 0x60, 0x3c,
	0xcb, 0xf9, 0x6c, 0x22, 0x59, 0x56, 0x67, 0x12, 0x4a, 0x67, 0x2c, 0xb3, 0xd6, 0x64, 0xb9, 0x36,
	0x2e, 0x51, 0x7f, 0x0b, 0x16, 0x98, 0x3c, 0x82, 0x8e, 0x2c, 0x18, 0x47, 0xc3, 0x54, 0xe5, 0x12,
	0x69, 0x27, 0x7f, 0x0a, 0xf1, 0x73, 0xd8, 0x0f, 0xd3, 0x56, 0x9f, 0x59, 0x89, 0x09, 0x7e, 0x9f,
	0xa3, 0x36, 0xeb, 0xa6, 0x88, 0x47, 0x70, 0xcf, 0x53, 0xf5, 0x28, 0x68, 0xd7, 0xec, 0x03, 0xd8,
	0xb6, 0x8c, 0x37, 0x81, 0xee, 0x41, 0x5d, 0x1d, 0x86, 0x79, 0x3d, 0x88, 0x3f, 0xc0, 0xc1, 0x5f,
	0x2a, 0xb2, 0xa8, 0x2c, 0x1b, 0x95, 0x12, 0xaa, 0xd6, 0x70, 0x60, 0x65, 0xb1, 0xc6, 0xea, 0x62,
	0xf1, 0x17, 0x20, 0x2b, 0xc1, 0x6e, 0xd2, 0x79, 0x09, 0x2d, 0xed, 0x59, 0x21, 0x60, 0xe2, 0x12,
	0x5b, 0x3d, 0x5f, 0x53, 0xe2, 0x9f, 0x11, 0xdc, 0xbd, 0x15, 0x90, 0xde, 0xa4, 0xfe, 0x16, 0xda,
	0x3a, 0xd0, 0x68, 0x63, 0xd0, 0x5c, 0x5c, 0x88, 0x7f, 0x85, 0x9c, 0x2c, 0xe8, 0xe4, 0x05, 0xdc,
	0xd1, 0xf3, 0xd9, 0x0c, 0xb5, 0xc1, 0x2c, 0x5c, 0x2c, 0x4d, 0x9b, 0x83, 0xe6, 0x51, 0x27, 0xd9,
	0x5b, 0x34, 0x82, 0x61, 0xc3, 0x5f, 0x11, 0xf4, 0x4e, 0x47, 0x56, 0xe1, 0xbd, 0xfb, 0x51, 0x90,
	0x31, 0x74, 0xc7, 0x68, 0x6a, 0x23, 0xc9, 0xc3, 0xa5, 0xa5, 0x6e, 0x87, 0xd4, 0x7f, 0xb0, 0xbe,
	0x29, 0x8b, 0x2a, 0xfe, 0x8f, 0x8c, 0x61, 0x6f, 0x8c, 0x66, 0xf5, 0x3b, 0xa1, 0x4b, 0x07, 0x56,
	0x6e, 0x47, 0xff, 0xfe, 0x1a, 0xf3, 0x82, 0xd0, 0x27, 0xd8, 0xb7, 0x13, 0xdd, 0x32, 0x6f, 0x83,
	0x56, 0x7f, 0x9d, 0x53, 0x3a, 0xc8, 0x5d, 0xec, 0xb8, 0x5f, 0xe1, 0xc9, 0xef, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x1d, 0xf7, 0x93, 0xa9, 0x2b, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EDInfoCenterClient is the client API for EDInfoCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EDInfoCenterClient interface {
	GetDistance(ctx context.Context, in *SystemsDistanceRequest, opts ...grpc.CallOption) (*SystemsDistanceReply, error)
	GetSystemSummary(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*SystemSummaryReply, error)
	GetDockableStations(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*DockableStationsReply, error)
}

type eDInfoCenterClient struct {
	cc *grpc.ClientConn
}

func NewEDInfoCenterClient(cc *grpc.ClientConn) EDInfoCenterClient {
	return &eDInfoCenterClient{cc}
}

func (c *eDInfoCenterClient) GetDistance(ctx context.Context, in *SystemsDistanceRequest, opts ...grpc.CallOption) (*SystemsDistanceReply, error) {
	out := new(SystemsDistanceReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDInfoCenterClient) GetSystemSummary(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*SystemSummaryReply, error) {
	out := new(SystemSummaryReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetSystemSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDInfoCenterClient) GetDockableStations(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*DockableStationsReply, error) {
	out := new(DockableStationsReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetDockableStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EDInfoCenterServer is the server API for EDInfoCenter service.
type EDInfoCenterServer interface {
	GetDistance(context.Context, *SystemsDistanceRequest) (*SystemsDistanceReply, error)
	GetSystemSummary(context.Context, *SystemByNameRequest) (*SystemSummaryReply, error)
	GetDockableStations(context.Context, *SystemByNameRequest) (*DockableStationsReply, error)
}

func RegisterEDInfoCenterServer(s *grpc.Server, srv EDInfoCenterServer) {
	s.RegisterService(&_EDInfoCenter_serviceDesc, srv)
}

func _EDInfoCenter_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemsDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetDistance(ctx, req.(*SystemsDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDInfoCenter_GetSystemSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetSystemSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetSystemSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetSystemSummary(ctx, req.(*SystemByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDInfoCenter_GetDockableStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetDockableStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetDockableStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetDockableStations(ctx, req.(*SystemByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EDInfoCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EDInfoCenter",
	HandlerType: (*EDInfoCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDistance",
			Handler:    _EDInfoCenter_GetDistance_Handler,
		},
		{
			MethodName: "GetSystemSummary",
			Handler:    _EDInfoCenter_GetSystemSummary_Handler,
		},
		{
			MethodName: "GetDockableStations",
			Handler:    _EDInfoCenter_GetDockableStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf-spec/edicenter.proto",
}
