// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protobuf-spec/edicenter.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Point3D struct {
	X                    float64  `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    float64  `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Z                    float64  `protobuf:"fixed64,3,opt,name=z,proto3" json:"z,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Point3D) Reset()         { *m = Point3D{} }
func (m *Point3D) String() string { return proto.CompactTextString(m) }
func (*Point3D) ProtoMessage()    {}
func (*Point3D) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{0}
}

func (m *Point3D) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Point3D.Unmarshal(m, b)
}
func (m *Point3D) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Point3D.Marshal(b, m, deterministic)
}
func (m *Point3D) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Point3D.Merge(m, src)
}
func (m *Point3D) XXX_Size() int {
	return xxx_messageInfo_Point3D.Size(m)
}
func (m *Point3D) XXX_DiscardUnknown() {
	xxx_messageInfo_Point3D.DiscardUnknown(m)
}

var xxx_messageInfo_Point3D proto.InternalMessageInfo

func (m *Point3D) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Point3D) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Point3D) GetZ() float64 {
	if m != nil {
		return m.Z
	}
	return 0
}

type PopulatedSystemBriefInfo struct {
	Allegiance           string   `protobuf:"bytes,1,opt,name=allegiance,proto3" json:"allegiance,omitempty"`
	Government           string   `protobuf:"bytes,2,opt,name=government,proto3" json:"government,omitempty"`
	Faction              string   `protobuf:"bytes,3,opt,name=faction,proto3" json:"faction,omitempty"`
	FactionState         string   `protobuf:"bytes,4,opt,name=faction_state,json=factionState,proto3" json:"faction_state,omitempty"`
	Population           int64    `protobuf:"varint,5,opt,name=population,proto3" json:"population,omitempty"`
	Reserve              string   `protobuf:"bytes,6,opt,name=reserve,proto3" json:"reserve,omitempty"`
	Security             string   `protobuf:"bytes,7,opt,name=security,proto3" json:"security,omitempty"`
	Economy              string   `protobuf:"bytes,8,opt,name=economy,proto3" json:"economy,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PopulatedSystemBriefInfo) Reset()         { *m = PopulatedSystemBriefInfo{} }
func (m *PopulatedSystemBriefInfo) String() string { return proto.CompactTextString(m) }
func (*PopulatedSystemBriefInfo) ProtoMessage()    {}
func (*PopulatedSystemBriefInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{1}
}

func (m *PopulatedSystemBriefInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PopulatedSystemBriefInfo.Unmarshal(m, b)
}
func (m *PopulatedSystemBriefInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PopulatedSystemBriefInfo.Marshal(b, m, deterministic)
}
func (m *PopulatedSystemBriefInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PopulatedSystemBriefInfo.Merge(m, src)
}
func (m *PopulatedSystemBriefInfo) XXX_Size() int {
	return xxx_messageInfo_PopulatedSystemBriefInfo.Size(m)
}
func (m *PopulatedSystemBriefInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PopulatedSystemBriefInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PopulatedSystemBriefInfo proto.InternalMessageInfo

func (m *PopulatedSystemBriefInfo) GetAllegiance() string {
	if m != nil {
		return m.Allegiance
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetGovernment() string {
	if m != nil {
		return m.Government
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetFaction() string {
	if m != nil {
		return m.Faction
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetFactionState() string {
	if m != nil {
		return m.FactionState
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetPopulation() int64 {
	if m != nil {
		return m.Population
	}
	return 0
}

func (m *PopulatedSystemBriefInfo) GetReserve() string {
	if m != nil {
		return m.Reserve
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetSecurity() string {
	if m != nil {
		return m.Security
	}
	return ""
}

func (m *PopulatedSystemBriefInfo) GetEconomy() string {
	if m != nil {
		return m.Economy
	}
	return ""
}

type SystemSummary struct {
	Name                 string                    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Coords               *Point3D                  `protobuf:"bytes,2,opt,name=coords,proto3" json:"coords,omitempty"`
	PopSystemInfo        *PopulatedSystemBriefInfo `protobuf:"bytes,3,opt,name=pop_system_info,json=popSystemInfo,proto3" json:"pop_system_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *SystemSummary) Reset()         { *m = SystemSummary{} }
func (m *SystemSummary) String() string { return proto.CompactTextString(m) }
func (*SystemSummary) ProtoMessage()    {}
func (*SystemSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{2}
}

func (m *SystemSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemSummary.Unmarshal(m, b)
}
func (m *SystemSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemSummary.Marshal(b, m, deterministic)
}
func (m *SystemSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemSummary.Merge(m, src)
}
func (m *SystemSummary) XXX_Size() int {
	return xxx_messageInfo_SystemSummary.Size(m)
}
func (m *SystemSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemSummary.DiscardUnknown(m)
}

var xxx_messageInfo_SystemSummary proto.InternalMessageInfo

func (m *SystemSummary) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SystemSummary) GetCoords() *Point3D {
	if m != nil {
		return m.Coords
	}
	return nil
}

func (m *SystemSummary) GetPopSystemInfo() *PopulatedSystemBriefInfo {
	if m != nil {
		return m.PopSystemInfo
	}
	return nil
}

type DockableStationShortInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LandingPad           string   `protobuf:"bytes,2,opt,name=landing_pad,json=landingPad,proto3" json:"landing_pad,omitempty"`
	Distance             float64  `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	Planetary            bool     `protobuf:"varint,4,opt,name=planetary,proto3" json:"planetary,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DockableStationShortInfo) Reset()         { *m = DockableStationShortInfo{} }
func (m *DockableStationShortInfo) String() string { return proto.CompactTextString(m) }
func (*DockableStationShortInfo) ProtoMessage()    {}
func (*DockableStationShortInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{3}
}

func (m *DockableStationShortInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockableStationShortInfo.Unmarshal(m, b)
}
func (m *DockableStationShortInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockableStationShortInfo.Marshal(b, m, deterministic)
}
func (m *DockableStationShortInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockableStationShortInfo.Merge(m, src)
}
func (m *DockableStationShortInfo) XXX_Size() int {
	return xxx_messageInfo_DockableStationShortInfo.Size(m)
}
func (m *DockableStationShortInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DockableStationShortInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DockableStationShortInfo proto.InternalMessageInfo

func (m *DockableStationShortInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DockableStationShortInfo) GetLandingPad() string {
	if m != nil {
		return m.LandingPad
	}
	return ""
}

func (m *DockableStationShortInfo) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

func (m *DockableStationShortInfo) GetPlanetary() bool {
	if m != nil {
		return m.Planetary
	}
	return false
}

type HumanWorldStat struct {
	Systems              int64    `protobuf:"varint,1,opt,name=systems,proto3" json:"systems,omitempty"`
	Stations             int64    `protobuf:"varint,2,opt,name=stations,proto3" json:"stations,omitempty"`
	Factions             int64    `protobuf:"varint,3,opt,name=factions,proto3" json:"factions,omitempty"`
	HumanFactions        int64    `protobuf:"varint,4,opt,name=human_factions,json=humanFactions,proto3" json:"human_factions,omitempty"`
	Population           int64    `protobuf:"varint,5,opt,name=population,proto3" json:"population,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HumanWorldStat) Reset()         { *m = HumanWorldStat{} }
func (m *HumanWorldStat) String() string { return proto.CompactTextString(m) }
func (*HumanWorldStat) ProtoMessage()    {}
func (*HumanWorldStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{4}
}

func (m *HumanWorldStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HumanWorldStat.Unmarshal(m, b)
}
func (m *HumanWorldStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HumanWorldStat.Marshal(b, m, deterministic)
}
func (m *HumanWorldStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HumanWorldStat.Merge(m, src)
}
func (m *HumanWorldStat) XXX_Size() int {
	return xxx_messageInfo_HumanWorldStat.Size(m)
}
func (m *HumanWorldStat) XXX_DiscardUnknown() {
	xxx_messageInfo_HumanWorldStat.DiscardUnknown(m)
}

var xxx_messageInfo_HumanWorldStat proto.InternalMessageInfo

func (m *HumanWorldStat) GetSystems() int64 {
	if m != nil {
		return m.Systems
	}
	return 0
}

func (m *HumanWorldStat) GetStations() int64 {
	if m != nil {
		return m.Stations
	}
	return 0
}

func (m *HumanWorldStat) GetFactions() int64 {
	if m != nil {
		return m.Factions
	}
	return 0
}

func (m *HumanWorldStat) GetHumanFactions() int64 {
	if m != nil {
		return m.HumanFactions
	}
	return 0
}

func (m *HumanWorldStat) GetPopulation() int64 {
	if m != nil {
		return m.Population
	}
	return 0
}

type ShortFactionState struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	State                string   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Allegiance           string   `protobuf:"bytes,3,opt,name=allegiance,proto3" json:"allegiance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShortFactionState) Reset()         { *m = ShortFactionState{} }
func (m *ShortFactionState) String() string { return proto.CompactTextString(m) }
func (*ShortFactionState) ProtoMessage()    {}
func (*ShortFactionState) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{5}
}

func (m *ShortFactionState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShortFactionState.Unmarshal(m, b)
}
func (m *ShortFactionState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShortFactionState.Marshal(b, m, deterministic)
}
func (m *ShortFactionState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShortFactionState.Merge(m, src)
}
func (m *ShortFactionState) XXX_Size() int {
	return xxx_messageInfo_ShortFactionState.Size(m)
}
func (m *ShortFactionState) XXX_DiscardUnknown() {
	xxx_messageInfo_ShortFactionState.DiscardUnknown(m)
}

var xxx_messageInfo_ShortFactionState proto.InternalMessageInfo

func (m *ShortFactionState) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ShortFactionState) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ShortFactionState) GetAllegiance() string {
	if m != nil {
		return m.Allegiance
	}
	return ""
}

type InterestingSystem4State struct {
	Name                 string               `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Coords               *Point3D             `protobuf:"bytes,2,opt,name=coords,proto3" json:"coords,omitempty"`
	Population           int64                `protobuf:"varint,3,opt,name=population,proto3" json:"population,omitempty"`
	FactionStates        []*ShortFactionState `protobuf:"bytes,4,rep,name=faction_states,json=factionStates,proto3" json:"faction_states,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *InterestingSystem4State) Reset()         { *m = InterestingSystem4State{} }
func (m *InterestingSystem4State) String() string { return proto.CompactTextString(m) }
func (*InterestingSystem4State) ProtoMessage()    {}
func (*InterestingSystem4State) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{6}
}

func (m *InterestingSystem4State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterestingSystem4State.Unmarshal(m, b)
}
func (m *InterestingSystem4State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterestingSystem4State.Marshal(b, m, deterministic)
}
func (m *InterestingSystem4State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterestingSystem4State.Merge(m, src)
}
func (m *InterestingSystem4State) XXX_Size() int {
	return xxx_messageInfo_InterestingSystem4State.Size(m)
}
func (m *InterestingSystem4State) XXX_DiscardUnknown() {
	xxx_messageInfo_InterestingSystem4State.DiscardUnknown(m)
}

var xxx_messageInfo_InterestingSystem4State proto.InternalMessageInfo

func (m *InterestingSystem4State) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterestingSystem4State) GetCoords() *Point3D {
	if m != nil {
		return m.Coords
	}
	return nil
}

func (m *InterestingSystem4State) GetPopulation() int64 {
	if m != nil {
		return m.Population
	}
	return 0
}

func (m *InterestingSystem4State) GetFactionStates() []*ShortFactionState {
	if m != nil {
		return m.FactionStates
	}
	return nil
}

type SystemByNameRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemByNameRequest) Reset()         { *m = SystemByNameRequest{} }
func (m *SystemByNameRequest) String() string { return proto.CompactTextString(m) }
func (*SystemByNameRequest) ProtoMessage()    {}
func (*SystemByNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{7}
}

func (m *SystemByNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemByNameRequest.Unmarshal(m, b)
}
func (m *SystemByNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemByNameRequest.Marshal(b, m, deterministic)
}
func (m *SystemByNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemByNameRequest.Merge(m, src)
}
func (m *SystemByNameRequest) XXX_Size() int {
	return xxx_messageInfo_SystemByNameRequest.Size(m)
}
func (m *SystemByNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemByNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemByNameRequest proto.InternalMessageInfo

func (m *SystemByNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SystemsDistanceRequest struct {
	Name1                string   `protobuf:"bytes,1,opt,name=name1,proto3" json:"name1,omitempty"`
	Name2                string   `protobuf:"bytes,2,opt,name=name2,proto3" json:"name2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemsDistanceRequest) Reset()         { *m = SystemsDistanceRequest{} }
func (m *SystemsDistanceRequest) String() string { return proto.CompactTextString(m) }
func (*SystemsDistanceRequest) ProtoMessage()    {}
func (*SystemsDistanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{8}
}

func (m *SystemsDistanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemsDistanceRequest.Unmarshal(m, b)
}
func (m *SystemsDistanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemsDistanceRequest.Marshal(b, m, deterministic)
}
func (m *SystemsDistanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemsDistanceRequest.Merge(m, src)
}
func (m *SystemsDistanceRequest) XXX_Size() int {
	return xxx_messageInfo_SystemsDistanceRequest.Size(m)
}
func (m *SystemsDistanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemsDistanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemsDistanceRequest proto.InternalMessageInfo

func (m *SystemsDistanceRequest) GetName1() string {
	if m != nil {
		return m.Name1
	}
	return ""
}

func (m *SystemsDistanceRequest) GetName2() string {
	if m != nil {
		return m.Name2
	}
	return ""
}

type SystemsDistanceReply struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Distance             float64  `protobuf:"fixed64,2,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemsDistanceReply) Reset()         { *m = SystemsDistanceReply{} }
func (m *SystemsDistanceReply) String() string { return proto.CompactTextString(m) }
func (*SystemsDistanceReply) ProtoMessage()    {}
func (*SystemsDistanceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{9}
}

func (m *SystemsDistanceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemsDistanceReply.Unmarshal(m, b)
}
func (m *SystemsDistanceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemsDistanceReply.Marshal(b, m, deterministic)
}
func (m *SystemsDistanceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemsDistanceReply.Merge(m, src)
}
func (m *SystemsDistanceReply) XXX_Size() int {
	return xxx_messageInfo_SystemsDistanceReply.Size(m)
}
func (m *SystemsDistanceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemsDistanceReply.DiscardUnknown(m)
}

var xxx_messageInfo_SystemsDistanceReply proto.InternalMessageInfo

func (m *SystemsDistanceReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SystemsDistanceReply) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type SystemSummaryReply struct {
	Error                string         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Summary              *SystemSummary `protobuf:"bytes,2,opt,name=summary,proto3" json:"summary,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SystemSummaryReply) Reset()         { *m = SystemSummaryReply{} }
func (m *SystemSummaryReply) String() string { return proto.CompactTextString(m) }
func (*SystemSummaryReply) ProtoMessage()    {}
func (*SystemSummaryReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{10}
}

func (m *SystemSummaryReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemSummaryReply.Unmarshal(m, b)
}
func (m *SystemSummaryReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemSummaryReply.Marshal(b, m, deterministic)
}
func (m *SystemSummaryReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemSummaryReply.Merge(m, src)
}
func (m *SystemSummaryReply) XXX_Size() int {
	return xxx_messageInfo_SystemSummaryReply.Size(m)
}
func (m *SystemSummaryReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemSummaryReply.DiscardUnknown(m)
}

var xxx_messageInfo_SystemSummaryReply proto.InternalMessageInfo

func (m *SystemSummaryReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *SystemSummaryReply) GetSummary() *SystemSummary {
	if m != nil {
		return m.Summary
	}
	return nil
}

type DockableStationsReply struct {
	Error                string                      `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Stations             []*DockableStationShortInfo `protobuf:"bytes,2,rep,name=stations,proto3" json:"stations,omitempty"`
	SuggestedSystems     []string                    `protobuf:"bytes,3,rep,name=suggested_systems,json=suggestedSystems,proto3" json:"suggested_systems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *DockableStationsReply) Reset()         { *m = DockableStationsReply{} }
func (m *DockableStationsReply) String() string { return proto.CompactTextString(m) }
func (*DockableStationsReply) ProtoMessage()    {}
func (*DockableStationsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{11}
}

func (m *DockableStationsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DockableStationsReply.Unmarshal(m, b)
}
func (m *DockableStationsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DockableStationsReply.Marshal(b, m, deterministic)
}
func (m *DockableStationsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DockableStationsReply.Merge(m, src)
}
func (m *DockableStationsReply) XXX_Size() int {
	return xxx_messageInfo_DockableStationsReply.Size(m)
}
func (m *DockableStationsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_DockableStationsReply.DiscardUnknown(m)
}

var xxx_messageInfo_DockableStationsReply proto.InternalMessageInfo

func (m *DockableStationsReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *DockableStationsReply) GetStations() []*DockableStationShortInfo {
	if m != nil {
		return m.Stations
	}
	return nil
}

func (m *DockableStationsReply) GetSuggestedSystems() []string {
	if m != nil {
		return m.SuggestedSystems
	}
	return nil
}

type MostVisitedSystemsRequest struct {
	Origin               string   `protobuf:"bytes,1,opt,name=origin,proto3" json:"origin,omitempty"`
	MaxDistance          float64  `protobuf:"fixed64,2,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`
	MaxAge               int64    `protobuf:"varint,3,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Limit                int64    `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MostVisitedSystemsRequest) Reset()         { *m = MostVisitedSystemsRequest{} }
func (m *MostVisitedSystemsRequest) String() string { return proto.CompactTextString(m) }
func (*MostVisitedSystemsRequest) ProtoMessage()    {}
func (*MostVisitedSystemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{12}
}

func (m *MostVisitedSystemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MostVisitedSystemsRequest.Unmarshal(m, b)
}
func (m *MostVisitedSystemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MostVisitedSystemsRequest.Marshal(b, m, deterministic)
}
func (m *MostVisitedSystemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MostVisitedSystemsRequest.Merge(m, src)
}
func (m *MostVisitedSystemsRequest) XXX_Size() int {
	return xxx_messageInfo_MostVisitedSystemsRequest.Size(m)
}
func (m *MostVisitedSystemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MostVisitedSystemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MostVisitedSystemsRequest proto.InternalMessageInfo

func (m *MostVisitedSystemsRequest) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *MostVisitedSystemsRequest) GetMaxDistance() float64 {
	if m != nil {
		return m.MaxDistance
	}
	return 0
}

func (m *MostVisitedSystemsRequest) GetMaxAge() int64 {
	if m != nil {
		return m.MaxAge
	}
	return 0
}

func (m *MostVisitedSystemsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type SystemVisitsStat struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count                int64    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Distance             float64  `protobuf:"fixed64,3,opt,name=distance,proto3" json:"distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemVisitsStat) Reset()         { *m = SystemVisitsStat{} }
func (m *SystemVisitsStat) String() string { return proto.CompactTextString(m) }
func (*SystemVisitsStat) ProtoMessage()    {}
func (*SystemVisitsStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{13}
}

func (m *SystemVisitsStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemVisitsStat.Unmarshal(m, b)
}
func (m *SystemVisitsStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemVisitsStat.Marshal(b, m, deterministic)
}
func (m *SystemVisitsStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemVisitsStat.Merge(m, src)
}
func (m *SystemVisitsStat) XXX_Size() int {
	return xxx_messageInfo_SystemVisitsStat.Size(m)
}
func (m *SystemVisitsStat) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemVisitsStat.DiscardUnknown(m)
}

var xxx_messageInfo_SystemVisitsStat proto.InternalMessageInfo

func (m *SystemVisitsStat) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SystemVisitsStat) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *SystemVisitsStat) GetDistance() float64 {
	if m != nil {
		return m.Distance
	}
	return 0
}

type MostVisitedSystemsReply struct {
	Error                string              `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	SystemVisitStat      []*SystemVisitsStat `protobuf:"bytes,2,rep,name=system_visit_stat,json=systemVisitStat,proto3" json:"system_visit_stat,omitempty"`
	TotalCount           int64               `protobuf:"varint,3,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *MostVisitedSystemsReply) Reset()         { *m = MostVisitedSystemsReply{} }
func (m *MostVisitedSystemsReply) String() string { return proto.CompactTextString(m) }
func (*MostVisitedSystemsReply) ProtoMessage()    {}
func (*MostVisitedSystemsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{14}
}

func (m *MostVisitedSystemsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MostVisitedSystemsReply.Unmarshal(m, b)
}
func (m *MostVisitedSystemsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MostVisitedSystemsReply.Marshal(b, m, deterministic)
}
func (m *MostVisitedSystemsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MostVisitedSystemsReply.Merge(m, src)
}
func (m *MostVisitedSystemsReply) XXX_Size() int {
	return xxx_messageInfo_MostVisitedSystemsReply.Size(m)
}
func (m *MostVisitedSystemsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_MostVisitedSystemsReply.DiscardUnknown(m)
}

var xxx_messageInfo_MostVisitedSystemsReply proto.InternalMessageInfo

func (m *MostVisitedSystemsReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *MostVisitedSystemsReply) GetSystemVisitStat() []*SystemVisitsStat {
	if m != nil {
		return m.SystemVisitStat
	}
	return nil
}

func (m *MostVisitedSystemsReply) GetTotalCount() int64 {
	if m != nil {
		return m.TotalCount
	}
	return 0
}

type InterestingSystem4StateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	States               []string `protobuf:"bytes,2,rep,name=states,proto3" json:"states,omitempty"`
	MinPop               int64    `protobuf:"varint,3,opt,name=min_pop,json=minPop,proto3" json:"min_pop,omitempty"`
	MaxDistance          float64  `protobuf:"fixed64,4,opt,name=max_distance,json=maxDistance,proto3" json:"max_distance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InterestingSystem4StateRequest) Reset()         { *m = InterestingSystem4StateRequest{} }
func (m *InterestingSystem4StateRequest) String() string { return proto.CompactTextString(m) }
func (*InterestingSystem4StateRequest) ProtoMessage()    {}
func (*InterestingSystem4StateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{15}
}

func (m *InterestingSystem4StateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterestingSystem4StateRequest.Unmarshal(m, b)
}
func (m *InterestingSystem4StateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterestingSystem4StateRequest.Marshal(b, m, deterministic)
}
func (m *InterestingSystem4StateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterestingSystem4StateRequest.Merge(m, src)
}
func (m *InterestingSystem4StateRequest) XXX_Size() int {
	return xxx_messageInfo_InterestingSystem4StateRequest.Size(m)
}
func (m *InterestingSystem4StateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InterestingSystem4StateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InterestingSystem4StateRequest proto.InternalMessageInfo

func (m *InterestingSystem4StateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *InterestingSystem4StateRequest) GetStates() []string {
	if m != nil {
		return m.States
	}
	return nil
}

func (m *InterestingSystem4StateRequest) GetMinPop() int64 {
	if m != nil {
		return m.MinPop
	}
	return 0
}

func (m *InterestingSystem4StateRequest) GetMaxDistance() float64 {
	if m != nil {
		return m.MaxDistance
	}
	return 0
}

type InterestingSystem4StateReply struct {
	Error                string                     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Systems              []*InterestingSystem4State `protobuf:"bytes,2,rep,name=systems,proto3" json:"systems,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *InterestingSystem4StateReply) Reset()         { *m = InterestingSystem4StateReply{} }
func (m *InterestingSystem4StateReply) String() string { return proto.CompactTextString(m) }
func (*InterestingSystem4StateReply) ProtoMessage()    {}
func (*InterestingSystem4StateReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e4ecdf5e536227fd, []int{16}
}

func (m *InterestingSystem4StateReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InterestingSystem4StateReply.Unmarshal(m, b)
}
func (m *InterestingSystem4StateReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InterestingSystem4StateReply.Marshal(b, m, deterministic)
}
func (m *InterestingSystem4StateReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InterestingSystem4StateReply.Merge(m, src)
}
func (m *InterestingSystem4StateReply) XXX_Size() int {
	return xxx_messageInfo_InterestingSystem4StateReply.Size(m)
}
func (m *InterestingSystem4StateReply) XXX_DiscardUnknown() {
	xxx_messageInfo_InterestingSystem4StateReply.DiscardUnknown(m)
}

var xxx_messageInfo_InterestingSystem4StateReply proto.InternalMessageInfo

func (m *InterestingSystem4StateReply) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *InterestingSystem4StateReply) GetSystems() []*InterestingSystem4State {
	if m != nil {
		return m.Systems
	}
	return nil
}

func init() {
	proto.RegisterType((*Point3D)(nil), "api.Point3D")
	proto.RegisterType((*PopulatedSystemBriefInfo)(nil), "api.PopulatedSystemBriefInfo")
	proto.RegisterType((*SystemSummary)(nil), "api.SystemSummary")
	proto.RegisterType((*DockableStationShortInfo)(nil), "api.DockableStationShortInfo")
	proto.RegisterType((*HumanWorldStat)(nil), "api.HumanWorldStat")
	proto.RegisterType((*ShortFactionState)(nil), "api.ShortFactionState")
	proto.RegisterType((*InterestingSystem4State)(nil), "api.InterestingSystem4State")
	proto.RegisterType((*SystemByNameRequest)(nil), "api.SystemByNameRequest")
	proto.RegisterType((*SystemsDistanceRequest)(nil), "api.SystemsDistanceRequest")
	proto.RegisterType((*SystemsDistanceReply)(nil), "api.SystemsDistanceReply")
	proto.RegisterType((*SystemSummaryReply)(nil), "api.SystemSummaryReply")
	proto.RegisterType((*DockableStationsReply)(nil), "api.DockableStationsReply")
	proto.RegisterType((*MostVisitedSystemsRequest)(nil), "api.MostVisitedSystemsRequest")
	proto.RegisterType((*SystemVisitsStat)(nil), "api.SystemVisitsStat")
	proto.RegisterType((*MostVisitedSystemsReply)(nil), "api.MostVisitedSystemsReply")
	proto.RegisterType((*InterestingSystem4StateRequest)(nil), "api.InterestingSystem4StateRequest")
	proto.RegisterType((*InterestingSystem4StateReply)(nil), "api.InterestingSystem4StateReply")
}

func init() { proto.RegisterFile("protobuf-spec/edicenter.proto", fileDescriptor_e4ecdf5e536227fd) }

var fileDescriptor_e4ecdf5e536227fd = []byte{
	// 1016 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x4d, 0x6f, 0xdb, 0x46,
	0x10, 0x0d, 0x4d, 0x5b, 0xb2, 0x46, 0x92, 0x63, 0xaf, 0xbf, 0x18, 0xc5, 0x71, 0x9c, 0x4d, 0x0b,
	0xb8, 0x68, 0x2b, 0xa3, 0x72, 0x51, 0xa0, 0x87, 0x1e, 0x92, 0xc8, 0x51, 0x72, 0x48, 0x61, 0xd0,
	0x40, 0x93, 0x4b, 0x21, 0xac, 0xa5, 0x15, 0xb3, 0x28, 0xc9, 0x65, 0xb9, 0x2b, 0x43, 0xcc, 0xbd,
	0x40, 0x73, 0x2b, 0x50, 0xf4, 0x47, 0xf4, 0xda, 0xdf, 0xd6, 0x1f, 0x50, 0xec, 0x07, 0x25, 0x51,
	0x12, 0xd5, 0xdc, 0xf8, 0x66, 0x67, 0x67, 0x67, 0xdf, 0xbc, 0x47, 0x12, 0x1e, 0x25, 0x29, 0x97,
	0xfc, 0x76, 0x3c, 0xfa, 0x5a, 0x24, 0x74, 0x70, 0x41, 0x87, 0x6c, 0x40, 0x63, 0x49, 0xd3, 0xb6,
	0x8e, 0x23, 0x97, 0x24, 0xac, 0xf5, 0x30, 0xe0, 0x3c, 0x08, 0xe9, 0x45, 0x9e, 0x7a, 0x41, 0xa3,
	0x44, 0x66, 0x26, 0x03, 0x5f, 0x42, 0xf5, 0x9a, 0xb3, 0x58, 0x5e, 0x76, 0x51, 0x03, 0x9c, 0x89,
	0xe7, 0x9c, 0x39, 0xe7, 0x8e, 0xef, 0x4c, 0x14, 0xca, 0xbc, 0x0d, 0x83, 0x32, 0x85, 0x3e, 0x78,
	0xae, 0x41, 0x1f, 0xf0, 0xc7, 0x0d, 0xf0, 0xae, 0x79, 0x32, 0x0e, 0x89, 0xa4, 0xc3, 0x9b, 0x4c,
	0x48, 0x1a, 0x3d, 0x4f, 0x19, 0x1d, 0xbd, 0x8e, 0x47, 0x1c, 0x9d, 0x02, 0x90, 0x30, 0xa4, 0x01,
	0x23, 0xf1, 0x80, 0xea, 0x7a, 0x35, 0x7f, 0x2e, 0xa2, 0xd6, 0x03, 0x7e, 0x47, 0xd3, 0x38, 0xa2,
	0xb1, 0xd4, 0x27, 0xd4, 0xfc, 0xb9, 0x08, 0xf2, 0xa0, 0x3a, 0x22, 0x03, 0xc9, 0x78, 0xac, 0x0f,
	0xac, 0xf9, 0x39, 0x44, 0x4f, 0xa1, 0x69, 0x1f, 0xfb, 0x42, 0x12, 0x49, 0xbd, 0x4d, 0xbd, 0xde,
	0xb0, 0xc1, 0x1b, 0x15, 0x53, 0xe5, 0x13, 0xd3, 0x9a, 0xaa, 0xb0, 0x75, 0xe6, 0x9c, 0xbb, 0xfe,
	0x5c, 0x44, 0x95, 0x4f, 0xa9, 0xa0, 0xe9, 0x1d, 0xf5, 0x2a, 0xa6, 0xbc, 0x85, 0xa8, 0x05, 0xdb,
	0x82, 0x0e, 0xc6, 0x29, 0x93, 0x99, 0x57, 0xd5, 0x4b, 0x53, 0xac, 0x76, 0xd1, 0x01, 0x8f, 0x79,
	0x94, 0x79, 0xdb, 0x66, 0x97, 0x85, 0xf8, 0x0f, 0x07, 0x9a, 0x86, 0x82, 0x9b, 0x71, 0x14, 0x91,
	0x34, 0x43, 0x08, 0x36, 0x63, 0x12, 0xe5, 0x57, 0xd7, 0xcf, 0xe8, 0x33, 0xa8, 0x0c, 0x38, 0x4f,
	0x87, 0x42, 0x5f, 0xb8, 0xde, 0x69, 0xb4, 0x49, 0xc2, 0xda, 0x96, 0x79, 0xdf, 0xae, 0xa1, 0x2b,
	0xb8, 0x9f, 0xf0, 0xa4, 0x2f, 0x74, 0xb9, 0x3e, 0x8b, 0x47, 0x5c, 0x53, 0x50, 0xef, 0x3c, 0xb2,
	0xe9, 0xab, 0x29, 0xf7, 0x9b, 0x09, 0x4f, 0x4c, 0x4c, 0x41, 0xfc, 0xd1, 0x01, 0xaf, 0xcb, 0x07,
	0xbf, 0x90, 0xdb, 0x90, 0x2a, 0x52, 0x14, 0x37, 0xef, 0x79, 0x2a, 0xf5, 0x78, 0x56, 0x75, 0xf7,
	0x18, 0xea, 0x21, 0x89, 0x87, 0x2c, 0x0e, 0xfa, 0x09, 0x19, 0xe6, 0x33, 0xb1, 0xa1, 0x6b, 0x32,
	0x54, 0xd4, 0x0c, 0x99, 0x90, 0x7a, 0xa2, 0x46, 0x05, 0x53, 0x8c, 0x4e, 0xa0, 0x96, 0x84, 0x24,
	0xa6, 0x92, 0xa4, 0x99, 0x9e, 0xc8, 0xb6, 0x3f, 0x0b, 0xe0, 0xbf, 0x1d, 0xd8, 0x79, 0x35, 0x8e,
	0x48, 0xfc, 0x96, 0xa7, 0xe1, 0x50, 0x75, 0xa3, 0xb8, 0x34, 0x37, 0x14, 0xba, 0x09, 0xd7, 0xcf,
	0xa1, 0x9e, 0x80, 0xe9, 0xd7, 0xf0, 0xe4, 0xfa, 0x53, 0xac, 0xd6, 0xec, 0x9c, 0x85, 0x6e, 0xc1,
	0xf5, 0xa7, 0x18, 0x7d, 0x0e, 0x3b, 0xef, 0xd5, 0x19, 0xfd, 0x69, 0xc6, 0xa6, 0xce, 0x68, 0xea,
	0xe8, 0xcb, 0x3c, 0xed, 0x7f, 0xa4, 0x81, 0x7f, 0x86, 0x3d, 0xcd, 0xd3, 0xcb, 0x79, 0x3d, 0xad,
	0xe2, 0xeb, 0x00, 0xb6, 0x8c, 0x00, 0x0d, 0x53, 0x06, 0x2c, 0x08, 0xdf, 0x5d, 0x14, 0x3e, 0xfe,
	0xc7, 0x81, 0xe3, 0xd7, 0xca, 0x9c, 0x54, 0x48, 0x16, 0x07, 0x66, 0x60, 0xdf, 0x96, 0x9f, 0xf2,
	0x69, 0x9a, 0x29, 0x5e, 0xca, 0x5d, 0xd2, 0xfb, 0x0f, 0xb0, 0x53, 0x30, 0x8d, 0xe2, 0xc6, 0x3d,
	0xaf, 0x77, 0x8e, 0x74, 0xb5, 0xa5, 0xfb, 0xfa, 0xcd, 0x79, 0x37, 0x09, 0xfc, 0x05, 0xec, 0x5b,
	0xb5, 0x65, 0x3f, 0x92, 0x88, 0xfa, 0xf4, 0xd7, 0x31, 0x15, 0x72, 0x55, 0xbf, 0xb8, 0x0b, 0x47,
	0x26, 0x55, 0x74, 0xad, 0x36, 0xf2, 0xec, 0x03, 0xd8, 0x52, 0x19, 0xdf, 0xd8, 0x74, 0x03, 0xf2,
	0x68, 0x27, 0x67, 0x51, 0x03, 0xfc, 0x0a, 0x0e, 0x96, 0xaa, 0x24, 0x61, 0xa6, 0xb2, 0x69, 0x9a,
	0xf2, 0x34, 0xaf, 0xa1, 0x41, 0x41, 0x98, 0x1b, 0x45, 0x61, 0xe2, 0x77, 0x80, 0x0a, 0xc6, 0x5c,
	0x57, 0xe7, 0x2b, 0xa8, 0x0a, 0x93, 0x65, 0xc9, 0x46, 0x86, 0x9e, 0xc2, 0xfe, 0x3c, 0x05, 0xff,
	0xe5, 0xc0, 0xe1, 0x82, 0xc1, 0xc4, 0xba, 0xea, 0xdf, 0x17, 0x74, 0xed, 0x4e, 0x0d, 0x5d, 0x66,
	0xd2, 0x39, 0xd9, 0x7f, 0x09, 0x7b, 0x62, 0x1c, 0x04, 0x54, 0x48, 0x3a, 0xec, 0xe7, 0xb6, 0x71,
	0xcf, 0xdc, 0xf3, 0x9a, 0xbf, 0x3b, 0x5d, 0xb0, 0x84, 0xe1, 0xdf, 0x1c, 0x78, 0xf0, 0x86, 0x0b,
	0xf9, 0x13, 0x13, 0x6c, 0x16, 0xce, 0xa7, 0x70, 0x04, 0x15, 0x9e, 0xb2, 0x80, 0xc5, 0xb6, 0x39,
	0x8b, 0xd0, 0x13, 0x68, 0x44, 0x64, 0xd2, 0x5f, 0xe0, 0xb1, 0x1e, 0x91, 0x49, 0x3e, 0x01, 0x74,
	0x0c, 0x55, 0x95, 0x42, 0x02, 0x6a, 0x15, 0x56, 0x89, 0xc8, 0xe4, 0x59, 0xa0, 0x9d, 0x10, 0xb2,
	0x88, 0x49, 0x6b, 0x38, 0x03, 0xf0, 0x3b, 0xd8, 0x35, 0x67, 0xeb, 0x46, 0x84, 0x76, 0x7d, 0x89,
	0x8f, 0x06, 0x7c, 0x6c, 0xbf, 0x02, 0xae, 0x6f, 0xc0, 0xba, 0x97, 0x0d, 0xfe, 0xd3, 0x81, 0xe3,
	0x55, 0x37, 0x2c, 0xe7, 0xfe, 0x19, 0xec, 0xd9, 0xf7, 0xe9, 0x9d, 0xda, 0xa3, 0x4d, 0x60, 0x87,
	0x70, 0x38, 0x37, 0xe3, 0x59, 0xa7, 0xfe, 0x7d, 0x31, 0x8b, 0xe8, 0xd6, 0x1f, 0x43, 0x5d, 0x72,
	0x49, 0xc2, 0xbe, 0x69, 0xd6, 0x7a, 0x4c, 0x87, 0x5e, 0xa8, 0x08, 0xfe, 0xdd, 0x81, 0xd3, 0x12,
	0x67, 0xaf, 0x31, 0x8c, 0x1a, 0x88, 0xb5, 0xe4, 0x86, 0x1e, 0xa8, 0x45, 0x9a, 0x6d, 0x16, 0xf7,
	0x13, 0x9e, 0x4c, 0xd9, 0x66, 0xf1, 0x35, 0x4f, 0x96, 0x26, 0xb5, 0xb9, 0x34, 0x29, 0x1c, 0xc2,
	0x49, 0x69, 0x27, 0xe5, 0x24, 0x7d, 0x37, 0x7b, 0x25, 0x1b, 0x6a, 0x4e, 0x34, 0x35, 0x65, 0x95,
	0xf2, 0xe4, 0xce, 0xbf, 0x2e, 0x34, 0xae, 0xba, 0x4a, 0xb2, 0x2f, 0xf4, 0x6f, 0x07, 0xea, 0x41,
	0xbd, 0x47, 0xe5, 0x54, 0x37, 0x0f, 0xe7, 0x18, 0x5e, 0x7c, 0x2b, 0xb4, 0x1e, 0xac, 0x5e, 0x4c,
	0xc2, 0x0c, 0xdf, 0x43, 0x3d, 0xd8, 0xed, 0x51, 0x59, 0xfc, 0xb0, 0x7a, 0x73, 0x1b, 0x0a, 0xaf,
	0xa3, 0xd6, 0xf1, 0x0a, 0xb7, 0xda, 0x42, 0x6f, 0x60, 0x5f, 0x75, 0xb4, 0xe0, 0xd6, 0x35, 0xb5,
	0x5a, 0xab, 0xac, 0x29, 0xf2, 0x72, 0x6f, 0xe1, 0xb0, 0x47, 0xe5, 0xb2, 0x04, 0xd1, 0xa9, 0xde,
	0x56, 0xea, 0xbe, 0xd6, 0x49, 0xe9, 0xba, 0x29, 0x3c, 0x82, 0x56, 0x8f, 0xca, 0xb2, 0xef, 0xc3,
	0xd3, 0xb5, 0xf3, 0xb0, 0x47, 0x3c, 0x59, 0x9f, 0x64, 0xce, 0x79, 0x0e, 0x7b, 0x3d, 0x2a, 0x17,
	0x3e, 0xc9, 0x47, 0x6d, 0xf3, 0x8f, 0xd8, 0xce, 0xff, 0x11, 0xdb, 0x57, 0xea, 0x1f, 0xb1, 0xb5,
	0xaf, 0x2b, 0x16, 0x93, 0xf1, 0xbd, 0xdb, 0x8a, 0x4e, 0xbb, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff,
	0x0b, 0x38, 0xee, 0xa4, 0x7e, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EDInfoCenterClient is the client API for EDInfoCenter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EDInfoCenterClient interface {
	GetDistance(ctx context.Context, in *SystemsDistanceRequest, opts ...grpc.CallOption) (*SystemsDistanceReply, error)
	GetSystemSummary(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*SystemSummaryReply, error)
	GetDockableStations(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*DockableStationsReply, error)
	GetMostVisitedSystems(ctx context.Context, in *MostVisitedSystemsRequest, opts ...grpc.CallOption) (*MostVisitedSystemsReply, error)
	GetInterestingSystem4State(ctx context.Context, in *InterestingSystem4StateRequest, opts ...grpc.CallOption) (*InterestingSystem4StateReply, error)
	GetHumanWorldStat(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HumanWorldStat, error)
}

type eDInfoCenterClient struct {
	cc *grpc.ClientConn
}

func NewEDInfoCenterClient(cc *grpc.ClientConn) EDInfoCenterClient {
	return &eDInfoCenterClient{cc}
}

func (c *eDInfoCenterClient) GetDistance(ctx context.Context, in *SystemsDistanceRequest, opts ...grpc.CallOption) (*SystemsDistanceReply, error) {
	out := new(SystemsDistanceReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetDistance", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDInfoCenterClient) GetSystemSummary(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*SystemSummaryReply, error) {
	out := new(SystemSummaryReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetSystemSummary", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDInfoCenterClient) GetDockableStations(ctx context.Context, in *SystemByNameRequest, opts ...grpc.CallOption) (*DockableStationsReply, error) {
	out := new(DockableStationsReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetDockableStations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDInfoCenterClient) GetMostVisitedSystems(ctx context.Context, in *MostVisitedSystemsRequest, opts ...grpc.CallOption) (*MostVisitedSystemsReply, error) {
	out := new(MostVisitedSystemsReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetMostVisitedSystems", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDInfoCenterClient) GetInterestingSystem4State(ctx context.Context, in *InterestingSystem4StateRequest, opts ...grpc.CallOption) (*InterestingSystem4StateReply, error) {
	out := new(InterestingSystem4StateReply)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetInterestingSystem4State", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eDInfoCenterClient) GetHumanWorldStat(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*HumanWorldStat, error) {
	out := new(HumanWorldStat)
	err := c.cc.Invoke(ctx, "/api.EDInfoCenter/GetHumanWorldStat", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EDInfoCenterServer is the server API for EDInfoCenter service.
type EDInfoCenterServer interface {
	GetDistance(context.Context, *SystemsDistanceRequest) (*SystemsDistanceReply, error)
	GetSystemSummary(context.Context, *SystemByNameRequest) (*SystemSummaryReply, error)
	GetDockableStations(context.Context, *SystemByNameRequest) (*DockableStationsReply, error)
	GetMostVisitedSystems(context.Context, *MostVisitedSystemsRequest) (*MostVisitedSystemsReply, error)
	GetInterestingSystem4State(context.Context, *InterestingSystem4StateRequest) (*InterestingSystem4StateReply, error)
	GetHumanWorldStat(context.Context, *empty.Empty) (*HumanWorldStat, error)
}

func RegisterEDInfoCenterServer(s *grpc.Server, srv EDInfoCenterServer) {
	s.RegisterService(&_EDInfoCenter_serviceDesc, srv)
}

func _EDInfoCenter_GetDistance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemsDistanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetDistance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetDistance",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetDistance(ctx, req.(*SystemsDistanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDInfoCenter_GetSystemSummary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetSystemSummary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetSystemSummary",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetSystemSummary(ctx, req.(*SystemByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDInfoCenter_GetDockableStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SystemByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetDockableStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetDockableStations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetDockableStations(ctx, req.(*SystemByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDInfoCenter_GetMostVisitedSystems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MostVisitedSystemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetMostVisitedSystems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetMostVisitedSystems",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetMostVisitedSystems(ctx, req.(*MostVisitedSystemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDInfoCenter_GetInterestingSystem4State_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InterestingSystem4StateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetInterestingSystem4State(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetInterestingSystem4State",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetInterestingSystem4State(ctx, req.(*InterestingSystem4StateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EDInfoCenter_GetHumanWorldStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EDInfoCenterServer).GetHumanWorldStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.EDInfoCenter/GetHumanWorldStat",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EDInfoCenterServer).GetHumanWorldStat(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _EDInfoCenter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.EDInfoCenter",
	HandlerType: (*EDInfoCenterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDistance",
			Handler:    _EDInfoCenter_GetDistance_Handler,
		},
		{
			MethodName: "GetSystemSummary",
			Handler:    _EDInfoCenter_GetSystemSummary_Handler,
		},
		{
			MethodName: "GetDockableStations",
			Handler:    _EDInfoCenter_GetDockableStations_Handler,
		},
		{
			MethodName: "GetMostVisitedSystems",
			Handler:    _EDInfoCenter_GetMostVisitedSystems_Handler,
		},
		{
			MethodName: "GetInterestingSystem4State",
			Handler:    _EDInfoCenter_GetInterestingSystem4State_Handler,
		},
		{
			MethodName: "GetHumanWorldStat",
			Handler:    _EDInfoCenter_GetHumanWorldStat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf-spec/edicenter.proto",
}
